export const SERVER_INFO_CLEAR = 'SERVER_INFO_CLEAR'
export const SERVER_INFO_ERROR = 'SERVER_INFO_ERROR'
export const SERVER_INFO_IS_FETCHING = 'SERVER_INFO_IS_FETCHING'
export const SERVER_INFO_SET = 'SERVER_INFO_SET'
